Use {node, id} consistently in topology
phoenixframework/firenest pull request #20
Opened 2018-05-02 20:21 UTC by michalmuskala

* Remove extra guards from Erlang topology
* Use local state for topology broadcast in erlang topology instead of
  ets lookup
* Use public functions :net_kernel.connect_node and
  :erlang.disconnect_node for managing connection instead of private
  functions in :net_kernel

Closes #15

2018-05-03 11:20 UTC, josevalim commented on lib/firenest/topology/erlang.ex
> +    if node == Kernel.node() or node in node_names(topology) do
We need to check `{node, id}` here.

2018-05-03 12:06 UTC, josevalim requested changes
Just one commend and it should be good to go!

2018-05-03 12:26 UTC, michalmuskala commented
@josevalim I was wondering - is it fine to store the nodes in one row in ets, or should I optimise it, so we could use `:ets.member`?

2018-05-03 12:46 UTC, josevalim commented
Sounds good to me!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

2018-05-07 12:57 UTC, michalmuskala commented
Updated.

2018-05-07 13:28 UTC, josevalim approved these changes

2018-05-07 13:43 UTC, merged